name: 'SLATE'
tau_start: 1.0
tau_final: 0.1
tau_steps: 30000
hard: False
batch_size: 24
dropout: 0.1
use_augs: false
augment_samples: false
dataset_folder: null
pretrained_path: null
image_limits: [0, 1]

cnn_patch_dropout:
  min_patches_dropped: 0.
  max_patches_dropped: 0.5
  patch_dropout_proba: 0.

feature_dropout:
  min_features_dropped: 0.
  max_features_dropped: 0.5
  feature_dropout_proba: 0.

dvae:
  vocab_size: 4096
  d_model: 192

cnn:
  hidden_size: 64

slotattr:
  num_iterations: 3
  num_slots: ???
  num_slot_heads: 1
  slot_size: 128
  mlp_hidden_size: 192
  pos_channels: 4
  preinit_type: classic
  normalizer: null
  matching_loss:
    steps_into_future: 1
    use: False
    coef: 1.

tfdec:
  num_dec_blocks: 4
  num_dec_heads: 4

optimizer:
  global_oc_gradient_clip_val: 0.05
  global_oc_grad_clip_type: 'inf'
  encoder_optimizer:
    lr: 1e-4
    weight_decay: 0.05
    lr_scheduler:
      warmup_steps: 30_000
      decay_steps: 250_000
      type: exp
      decay_rate: 0.5

  slot_optimizer:
    lr: 1e-4
    weight_decay: 0.05
    lr_scheduler:
      warmup_steps: 30_000
      decay_steps: 250_000
      type: exp
      decay_rate: 0.5
  
  decoder_optimizer:
    lr: 3e-4
    weight_decay: 0.
    lr_scheduler:
      warmup_steps: 30_000
      decay_steps: 250_000
      type: exp
      decay_rate: 0.5

  dvae_optimizer:
    lr: 3e-4
    weight_decay: 0.05
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 250_000
      type: exp
      decay_rate: 1.