defaults:
  - _base
  - _self_

name: 'MLP'

ortho_init: False

# mlp stractor
backbone_net:
    dims: [64, 64]
    act: 'ReLU'
policy_net:
    dims: [64]
    act: 'Tanh'
value_net:
    dims: [64]
    act: 'Tanh'
