defaults:
  - _base
  - _self_
  - ocr: ???
  - pooling: ???
  - sb3: ???
  - sb3_acnet: ???
  - env: ???
  - comet: train_sb3

max_steps: 2e6

model_name: null
session_name: null
num_envs: 4

viz_interval: 30000
eval:
    freq: 12500
    n_episodes: 100
    video:
      qty: 5
      length: 1500

hydra:
  run:
    dir: ./outputs/train_sb3/${ocr.name}-${pooling.name}-${sb3.name}-${env.name}/hydra/${now:%Y-%m-%d_%H-%M-%S}
