defaults:
  - _base
  - _self_
  - ocr: ???
  - pooling: ???
  - sb3: ???
  - env: ???
  - comet: train_rl

max_steps: 500_000

dataset_root_path: ???
num_envs: 4

pretrained_model:
  use: False
  save_name: null
  step: null
  env: null

eval:
    freq: 12500
    n_episodes: 100
    video:
      qty: 5
      length: 1500

hydra:
  run:
    dir: ./outputs/train_rl/${ocr.name}-${pooling.name}-${sb3.name}-${env.name}/hydra/${now:%Y-%m-%d_%H-%M-%S}
