defaults:
    - _cw_env_base
    - _self_
name: CwTargetN4C4S11S1Env
env: CwTargetEnv

mode: 'hard'
target: []
check_collisions: False
#COLORS: ['blue', 'green', 'yellow', 'red']
COLORS: ['blue', 'green', 'yellow', 'red', 'orange', 'purple', 'brown', 'pink', 'gray', 'olive', 'cyan']


