obs_size: 64
obs_channels: 3
num_stacked_obss: 1
obs_type: 'dictstate'
object_size: 0.045
target_size: 0.04
robot_configuration: 'default'
viewpoint: 'frontview'
num_distractors: 4
rew_type: 'Sparse'
task: 'OddGroups'
tags: None
name: MuJoCoReach
env: MuJoCoReach
mode: None
num_objects_range: 4
action_repeat: 2
max_episode_steps: 50