defaults:
    - _synthetic_env_base
    - _self_
name: RandomObjsN5C4S4S2Env
env: RandomObjsEnv
num_objects_range: [5,5]
wo_agent: True
occlusion: True
agent_pos: null
COLORS: ['blue', 'green', 'yellow', 'red']
SHAPES: ['square', 'triangle', 'star_4', 'circle']
distance_to_agent: 3e-2
distance_to_objs: 3e-2
distance_to_wall: 3e-2
SCALES: [0.15, 0.22]
obs_size: ???